#!/bin/bash

# values from `id` command
# uid must be 1000 (no idea why - nothing else works)
user=1000 #$(($(id -u) + 1000))
user_name=$(id -un)
group=$(($(id -g) + 1000))
group_name=$(id -gn)
# run the container as a user to simplify writing files outside the container
cmd=${cmd:-nikola}
docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) -p 8000:8000 rbrewer123/nikola -U $user_name -u $user -G $group_name -g $group $cmd "$@"
